name: Bug Report
description: File a bug report
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - v1.0.0
        - v2.0.0
        - Main/Dev Branch
