name: Feature Request
description: Suggest an idea or a new feature for this project
title: "[Feature]: <Short descriptive title>"
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem-statement
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      placeholder: I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like the app to support...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I tried using X, but it didn't work because...

  - type: checkboxes
    id: contribution-confirmation
    attributes:
      label: Are you willing to help implement this feature?
      description: We are a community-driven project and welcome contributions!
      options:
        - label: Yes, I can work on this feature myself.
        - label: Yes, I can help with testing or documentation.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
